eureka:
 instance:
  prefer-ip-adress: true
   client:
    fetch-registry:true
    register-with-eureka=true
   service-url:
    defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
okta:
 oauth2:
  issuer: https://dev-08260882.okta.com/oauth2/default	
  audience: api://default
